export const TOGGLE_RECORD_PLAYBACK = "TOGGLE_RECORD_PLAYBACK";
export const START_RECORDING = "START_RECORDING";
export const STOP_RECORDING = "STOP_RECORDING";
export const START_PLAYING = "START_PLAYING";
export const STOP_PLAYING = "STOP_PLAYING";