export const TOGGLE_CONTROL_VIEW = "TOGGLE_CONTROL_VIEW";
export const START_RECORDING = "START_RECORDING";
export const START_PLAYING = "START_PLAYING";
export const ENTER_FOLDER = "ENTER_FOLDER";
export const CURRENT_FOLDER = "CURRENT_FOLDER";
export const GET_INITIAL_UNITS = "GET_INITIAL_UNITS";
export const SET_ACTIVE_FILE = "SET_ACTIVE_FILE";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const TOGGLE_OPTIONS = "TOGGLE_OPTIONS";
export const DELETE_UNIT = "DELETE_UNIT";
export const RENAME_UNIT = "RENAME_UNIT";


export const RECORD = "RECORD";
export const PLAYBACK = "PLAYBACK";
