export const TOGGLE_CONTROL_VIEW = "TOGGLE_CONTROL_VIEW";
export const ENTER_FOLDER = "ENTER_FOLDER";
export const SET_ACTIVE_FILE = "SET_ACTIVE_FILE";
export const TOGGLE_OPTIONS = "TOGGLE_OPTIONS";
export const DELETE_UNITS = "DELETE_UNITS";
export const MULTIPLE_MODE = "MULTIPLE_MODE";
export const MODIFY_SELECTED_UNIT = "MODIFY_SELECTED_UNIT";
export const READ_DIRECTORY = "READ_DIRECTORY"

export const RECORD = "RECORD";
export const PLAYBACK = "PLAYBACK";
